version: "3.9"
services:
  web:
    build: .
    env_file: .env
    depends_on: [redis]
  redis:
    image: redis:7-alpine
  nginx:
    image: nginx:alpine
    ports: ["80:80", "443:443"]
    volumes: ["./deploy/nginx.conf:/etc/nginx/conf.d/default.conf"]
    depends_on: [web]