FROM python:3.12-slim

ENV PYTHONDONTWRITEBYTECODE=1
WORKDIR /code

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

CMD ["flask", "--app=app", "run", "--host=0.0.0.0", "--port=8000", "--debug"]
