# version: 3.9
services:
  web:
    build: .
    command: >-
      gunicorn -k gevent -w 4 --worker-connections 1000
      --max-requests 1000 --max-requests-jitter 100
      -b 0.0.0.0:8000 wsgi:app
    env_file: .env
    depends_on: [db, redis]
    ports:
      - "8000:8000"

  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: eds
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: eds
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    restart: always

  nginx:
    image: nginx:1.27-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/vhost.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - web

volumes:
    pgdata:
