# version: 3.9
services:
  web:
    build: .
    env_file: .env
    depends_on: [db, redis]
    ports:
      - "8000:8000"
    command: >
      gunicorn -k gevent -w 2 -b 0.0.0.0:8000 wsgi:app

  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: eds
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: eds
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    restart: always

volumes:
    pgdata:

