version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile-dev  # swap to Dockerfile for prod
    ports:
      - "8080:8000"
    volumes:
      - .:/code
    environment:
      - FLASK_DEBUG=1
