"""add seq colum to chat_sessions

Revision ID: 0c2c80972352
Revises: 4e6bb6254373
Create Date: 2025-05-21 07:57:32.675736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c2c80972352'
down_revision = '4e6bb6254373'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_chat_sessions')
    with op.batch_alter_table('chat_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seq', sa.Integer(), nullable=False))
        batch_op.drop_constraint('fk_chat_sessions_visitor_id_users', type_='foreignkey')
        batch_op.drop_constraint('fk_chat_sessions_rep_id_users', type_='foreignkey')
        batch_op.drop_column('rep_id')
        batch_op.drop_column('visitor_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('visitor_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('rep_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_chat_sessions_rep_id_users', 'users', ['rep_id'], ['id'])
        batch_op.create_foreign_key('fk_chat_sessions_visitor_id_users', 'users', ['visitor_id'], ['id'])
        batch_op.drop_column('seq')

    op.create_table('_alembic_tmp_chat_sessions',
    sa.Column('id', sa.VARCHAR(length=32), nullable=False),
    sa.Column('opened_at', sa.DATETIME(), nullable=True),
    sa.Column('closed_at', sa.DATETIME(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('seq', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_chat_sessions_user_id_users'),
    sa.PrimaryKeyConstraint('id', name='pk_chat_sessions')
    )
    # ### end Alembic commands ###
