"""add waiting_desc to chat_session

Revision ID: 2e98e6d867a2
Revises: 4d303985bf08
Create Date: 2025-06-01 16:07:40.970289

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e98e6d867a2'
down_revision = '4d303985bf08'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table("chat_sessions") as batch_op:
        batch_op.add_column(
            sa.Column(
                "waiting_desc",
                sa.Boolean(),
                nullable=False,
                server_default=sa.text("0")      # ← 0 == False in SQLite
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_sessions', schema=None) as batch_op:
        batch_op.drop_column('waiting_desc')

    # ### end Alembic commands ###
