"""add seq column to chat_sessions

Revision ID: 4e6bb6254373
Revises: a71e0775fa2a
Create Date: 2025-05-21 07:51:01.128563

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e6bb6254373'
down_revision = 'a71e0775fa2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seq', sa.Integer(), nullable=False))
        batch_op.drop_constraint('fk_chat_sessions_visitor_id_users', type_='foreignkey')
        batch_op.drop_constraint('fk_chat_sessions_rep_id_users', type_='foreignkey')
        batch_op.drop_column('rep_id')
        batch_op.drop_column('visitor_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('visitor_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('rep_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_chat_sessions_rep_id_users', 'users', ['rep_id'], ['id'])
        batch_op.create_foreign_key('fk_chat_sessions_visitor_id_users', 'users', ['visitor_id'], ['id'])
        batch_op.drop_column('seq')

    # ### end Alembic commands ###
