"""added program applications table

Revision ID: 8f76476acd30
Revises: 7eaee69f5aab
Create Date: 2025-05-29 18:21:41.128292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f76476acd30'
down_revision = '7eaee69f5aab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('program_applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('program', sa.Enum('client', 'candidate', name='program_enum'), nullable=False),
    sa.Column('submitted', sa.DateTime(), nullable=True),
    sa.Column('street', sa.String(length=128), nullable=True),
    sa.Column('city', sa.String(length=64), nullable=True),
    sa.Column('state', sa.String(length=32), nullable=True),
    sa.Column('zip', sa.String(length=16), nullable=True),
    sa.Column('country', sa.String(length=64), nullable=True),
    sa.Column('occupation', sa.String(length=64), nullable=True),
    sa.Column('income_bracket', sa.String(length=32), nullable=True),
    sa.Column('education', sa.String(length=32), nullable=True),
    sa.Column('marital_status', sa.String(length=16), nullable=True),
    sa.Column('ref_src', sa.String(length=32), nullable=True),
    sa.Column('intro', sa.Text(), nullable=True),
    sa.Column('fee_paid', sa.Boolean(), nullable=True),
    sa.Column('stripe_pi', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_program_applications_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_program_applications'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('program_applications')
    # ### end Alembic commands ###
