"""add assigned_at to chat_sessions

Revision ID: 92cef7297cb9
Revises: eb500e59928b
Create Date: 2025-05-28 17:33:44.298512

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92cef7297cb9'
down_revision = 'eb500e59928b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assigned_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_sessions', schema=None) as batch_op:
        batch_op.drop_column('assigned_at')

    # ### end Alembic commands ###
