"""add phone_otpp fields

Revision ID: 94b0268bbd6a
Revises: 7a8134eb2525
Create Date: 2025-05-28 10:11:44.094471

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94b0268bbd6a'
down_revision = '7a8134eb2525'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_otp', sa.String(length=6), nullable=True))
        batch_op.add_column(sa.Column('phone_otp_sent', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('phone_otp_sent')
        batch_op.drop_column('phone_otp')

    # ### end Alembic commands ###
