"""add replied_via_email to ChatSession

Revision ID: b3eccb1a72c8
Revises: b5a82baba1d4
Create Date: 2025-05-30 14:10:33.472545

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3eccb1a72c8'
down_revision = 'b5a82baba1d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('replied_via_email', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_sessions', schema=None) as batch_op:
        batch_op.drop_column('replied_via_email')

    # ### end Alembic commands ###
