"""make message.ts timezone aware and indexed

Revision ID: b5a82baba1d4
Revises: 8f76476acd30
Create Date: 2025-05-30 11:12:14.262533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5a82baba1d4'
down_revision = '8f76476acd30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_messages_ts'), ['ts'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_messages_ts'))

    # ### end Alembic commands ###
