"""add is_rep flag

Revision ID: b74df587cdd4
Revises: 0c2c80972352
Create Date: 2025-05-22 10:56:53.429768

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b74df587cdd4'
down_revision = '0c2c80972352'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_rep', sa.Boolean(), nullable=False, server_default=sa.text('0')))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column("is_rep", server_default=None)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_rep')

    # ### end Alembic commands ###
