"""added chat rating

Revision ID: cf640cd022fa
Revises: 92cef7297cb9
Create Date: 2025-05-29 09:42:18.081216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf640cd022fa'
down_revision = '92cef7297cb9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rating', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_sessions', schema=None) as batch_op:
        batch_op.drop_column('rating')

    # ### end Alembic commands ###
